//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test_21032019
{
    using System;
    using System.Collections.Generic;
    
    public partial class komputery
    {
        public int komputerId { get; set; }
        public string firma { get; set; }
        public string dostawca { get; set; }
        public int zailacz { get; set; }
        public int uzykownikId { get; set; }
    
        public virtual uzytkownicy uzytkownicy { get; set; }
    }
}
